---

- name: apt install
  sudo: yes
  apt:
    name='{{item}}'
    state=latest
  with_items:
    - tree
    - vim
    - ansible


- name: create my_temp directory
  file: 
    path={{ansible_env.HOME}}/my_temp
    state=directory

- name: create my_linux directory
  file:
    path={{ansible_env.HOME}}/my_linux
    state=directory


- include: vim.yml
- include: ansible.yml
